name: Publish Smart-ui-vite To Npm

on:
  push:
    branches: [publish-smart-ui-vite]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish npm'
    environment: npm
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - name: Install modules
        run: cd packages/smart-ui-vite && pnpm install
      - name: Build
        run: cd packages/smart-ui-vite && pnpm run build
      - name: "Publish to the npm registry"
        uses: "primer/publish@3.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          dir: "packages/smart-ui-vite"
          default_branch: 'publish'